"""edit booking

Revision ID: 5371171eb23e
Revises: 75668988960f
Create Date: 2023-10-03 11:07:05.857324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5371171eb23e'
down_revision: Union[str, None] = '75668988960f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('under_name', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('bookings', sa.Column('comment', sa.String(), nullable=True))
    op.drop_column('bookings', 'first_name')
    op.drop_column('bookings', 'last_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('last_name', sa.VARCHAR(), nullable=True))
    op.add_column('bookings', sa.Column('first_name', sa.VARCHAR(), nullable=True))
    op.drop_column('bookings', 'comment')
    op.drop_column('bookings', 'date')
    op.drop_column('bookings', 'under_name')
    # ### end Alembic commands ###
